
################
# Device       #
################

# Search
http://127.0.0.1:8080/happ/device/search?id=6244f1aa4ef72ab5

# Update 
http://127.0.0.1:8080/happ/device/update?id=6244f1aa4ef72ab5&age=21&gender=WOMAN&maritalstatus=MARRIED&codeEducationLevel=BAS


################
# Envirotment  #
################

# Get alls EducationLevels
http://127.0.0.1:8080/happ/envirotment/educationLevels


################
# Questionary  #
################

# Get all questionary
http://127.0.0.1:8080/happ/questionary/all

# Find First Session By AndroidId forAnswer
http://127.0.0.1:8080/happ/questionary/session/forAnswer?id=6244f1aa4ef72ab5

# Answer session
http://127.0.0.1:8080/happ/questionary/session/answer?id=6244f1aa4ef72ab5&session=1&answer=2
http://127.0.0.1:8080/happ/questionary/session/answer?id=6244f1aa4ef72ab5&session=1&answer=8


################
# Valuation    #
################
http://127.0.0.1:8080/happ/valuation/list/21/01/2018?id=6244f1aa4ef72ab5
http://127.0.0.1:8080/happ/valuation/wellness/8/3?id=6244f1aa4ef72ab5
http://127.0.0.1:8080/happ/valuation/add/?id=6244f1aa4ef72ab5&text=holamundo






